### ISSUE TITLE
Implement roDateTime object

### ISSUE THREAD

**Issue by jweeber** [sjbarag/brs#129]
The brightscript roDateTime object and the methods associated with it are used often in many codebases, so we should implement it.

https://sdkdocs.roku.com/display/sdkdoc/ifDateTime

**Comment by sjbarag** [comment]
Thanks for opening this @jweeber !

**Comment by lvcabral** [comment]
I just finished to implement this one. Working on the unit tests now.

**Comment by lvcabral** [comment]
This issue can be closed as the PR was already merged.
