### ISSUE TITLE
Track start and end column numbers and filenames in Token

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#134]
Not having the column numbers and file locations for tokens was fine when things were only located in single (small) files, but the inputs to `brs` can now be much more substantial!  To make the parser (or interpreter)'s output more meaningful to users with multiple long files, we need to report with more granularity where errors occurred.

**Comment by sjbarag** [comment]
@TwitchBronBron found a bug in the WIP branch for column numbers:

```javascript
var brs = require('brs');
let lexResult = brs.lexer.Lexer.scan(`
    function DoSomething() as string
    end function
`);
let parseResult = brs.parser.Parser.parse(lexResult.tokens);
let func = parseResult.statements[0];
console.log(parseResult.statements[0]);
if (
    func.name.location.start.column !== 14 ||
    func.name.location.end.column !== 25
) {
    throw new Error('Incorrectly computed location for "DoSomething"');
}
```

> The end column of the function names are 1 number higher than they should be.

I was afraid of that :/

**Comment by sjbarag** [comment]
Another from @TwitchBronBron:

> Found another location bug (using your latest commits). This time, the end column of the callee location of a function call is 1 char LOWER than it should be.
>
>```javascript
> let lexResult = brs.lexer.Lexer.scan(`
> sub init()
>     ShowRectangle()
> end sub 
> `);
> let parseResult = brs.parser.Parser.parse(lexResult.tokens);
> let calleeLocation = parseResult.statements[0].func.body.statements[0].expression.callee.location
> console.log(calleeLocation);
> if (
>     calleeLocation.start.column !== 5 ||
>     calleeLocation.end.column !== 18
> ) {
>     throw new Error('Incorrectly computed location for "ShowRectangle"');
> }
> ```

**Comment by TwitchBronBron** [comment]
Your latest code seems to have fixed the `func.name.location` and `expression.callee.location` issues.
