### ISSUE TITLE
index.d.ts in npm module has import references to Users/sean.barag

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#137]
The index.d.ts file included in the npm module `brs@0.13.0-beta.0` includes some references to Users/sean.barag

![image](https://user-images.githubusercontent.com/2544493/51365310-aae04680-1aad-11e9-9e04-6bf97af278e7.png)

**Comment by sjbarag** [comment]
Oh heck – well this is embarrassing!  Thanks for letting me know 😄

**Comment by sjbarag** [comment]
Hey @TwitchBronBron – I just published `0.13.0-beta.2` which should include a less silly set of TypeScript declarations.  Thanks again!

**Comment by TwitchBronBron** [comment]
That did the trick. Thanks!
