### ISSUE TITLE
Add support for goto

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#158]
BrightScript supports `goto` statements, C-style!  They currently cause parse failures because an identifier followed by a `:` isn't supported as a statement.

From the spec: https://sdkdocs.roku.com/display/sdkdoc/Program+Statements#ProgramStatements-GOTOlabel

**Comment by TwitchBronBron** [comment]
You can assign this to me. Once #211 lands, I'll parser support. 

`goto` is keyword-ish, It can be used as a property on an object.

**Comment by TwitchBronBron** [comment]
@sjbarag I'm working on this.
