### ISSUE TITLE
Using `stop` keyword as object key causes parse errors

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#164]
This brightscript code causes a parse error because the `stop` keyword is not being interpreted as an identifier.

```brightscript
sub GetObject()
    obj = {
        stop: function() as void

        end function
    }
    return obj
end sub
```

![image](https://user-images.githubusercontent.com/2544493/53216723-87b43400-3623-11e9-9e1c-4a0746ec642f.png)

**Comment by sjbarag** [comment]
Great catch!  Pulling this into 0.13.0.
