### ISSUE TITLE
Bit shift assignment operators causing parse error

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#172]
I see you fixed most of the assignment operators in `v0.13.0-rc.3`. However, the bitshift operators are still causing issues.

```brightscript
function Main()
    x=1
    x <<= 8
    x >>= 4
    print x
end function
```

![image](https://user-images.githubusercontent.com/2544493/53299641-f8697500-380a-11e9-80c7-588b066a66b8.png)

**Comment by TwitchBronBron** [comment]
Also make sure to support object properties like: 

```brightscript
 function Main()
    m.x = 1
    m.x <<= 1
    m.x >>= 1
    m['x'] << 1
    m['x'] >> 1
    print m.x
end function
```

**Comment by sjbarag** [comment]
Bitshift operators in general don’t work right now. There’s no good reason that they don’t, I just never built them out while doing the initial pass of arithmetic operations. They’re next in line for support :)
