### ISSUE TITLE
Caret assignment operator not valid

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#176]
The caret equals (`^=`) operator was added to `brs` in [this commit](https://github.com/sjbarag/brs/commit/9cff49fd1387ca22bd4d34e022295777c8f1124d#diff-a13a274bb5ce98d0a99b2a3c4243ba46R192).

This does not appear to be valid brightscript. I can't find any reference in the docs, and it also produces a syntax error when compiling on a Roku device. I believe the `^=` assignment operator should be removed?

Here's a test file you can run on a Roku device which proves the code does not compile. 
```brightscript
function Main()
   age = 10
   age ^= 2
   print age
end function
```

**Comment by sjbarag** [comment]
Oh dang I must have mentally added it to the list from sdkdocs:
https://sdkdocs.roku.com/display/sdkdoc/Expressions%2C+Variables%2C+and+Types#Expressions,Variables,andTypes-MathematicalandBitshiftAssignmentOperators

Great catch!
