### ISSUE TITLE
property named "next" causes parse errors

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#194]
There is a parse error when using a property called `next` on an object. I just ran this on a roku, and it works.

![image](https://user-images.githubusercontent.com/2544493/54234001-879daa80-44e4-11e9-9a06-e851e3f36816.png)

**Comment by sjbarag** [comment]
Another in the family of #164 and #182, in which some keywords aren't reserved words and can be used for other purposes.  `next` likely needs to be lexed as an Identifier with text `next`, and anything that'd normally use `next` as a keyword has to look for an identifier instead.
