### ISSUE TITLE
Colon as separator between anonymous object properties

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#195]
Aparently brightscript allows you to use a colon to separate properties in objects. This is technically valid syntax. I tested each of these against a live roku, and they all printed the values out properly: 

![image](https://user-images.githubusercontent.com/2544493/54234321-45289d80-44e5-11e9-8516-7692b540e4c5.png)

So is this (colon and then newline): 
![image](https://user-images.githubusercontent.com/2544493/54234619-dbf55a00-44e5-11e9-801f-4be162d0ee63.png)

**Comment by sjbarag** [comment]
I'll never not be surprised by BrightScript!  This makes sense in the context that `:` is valid to separate… I guess statements (?), but it's certainly something I've never thought to try intentionally :smiley: 

Thanks for checking the newline cases for me as well! :heart:

**Comment by TwitchBronBron** [comment]
I'm working on this
