### ISSUE TITLE
Update jest to fix nightly builds

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#197]
Node 11.11 doesn't seem to play nicely with the slightly old version of `jest` we've got.  Upgrade to `jest@24.3.0` or greater to fix nightly builds.

More details in https://github.com/facebook/jest/issues/8069#issuecomment-470520613

(great now I show up in the "referenced this issue" list 😞)

**Comment by TwitchBronBron** [comment]
Can you update your build process to target a lower version of node instead? Doesn't seem to be worth pushing the upgrades if you can do that...should be a quick fix. 

Looking at this example: https://circleci.com/docs/2.0/language-javascript/#sample-configuration

they specify  

```
docker: # run the steps with Docker
      - image: circleci/node:4.8.2 #
```

by this logic, you could possibly just change that to the specific version of node that you know works.

**Comment by sjbarag** [comment]
Another node update took care of this soooooo…
