### ISSUE TITLE
Support numeric literal type designators

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#199]
According to [this page](https://sdkdocs.roku.com/display/sdkdoc/Expressions%2C+Variables%2C+and+Types#Expressions,Variables,andTypes-NumericLiterals), BrightScript supports declaring numeric literals. So this project should also support those. 

It appears that brs does support some of these, but the ampersand for integer and longinteger literals result in parse errors.

![image](https://user-images.githubusercontent.com/2544493/54275413-e9035f00-4560-11e9-8322-523d0be38a28.png)

**Comment by sjbarag** [comment]
Numeric literals are handled in the lexer, though this might require a little type system work to make the transition from hex to not-hex a little easier.
