### ISSUE TITLE
more than 1 space between for each causes parse error

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#202]
If there is more than one whitespace character between the `for` and `each`, that results in a parser error. However, this successfully compiles and runs on Roku.

![image](https://user-images.githubusercontent.com/2544493/54325232-87320c00-45d7-11e9-96c2-f3ec42a0eec2.png)

**Comment by sjbarag** [comment]
Well that's bizarre - I would have never thought to try that!  Thanks for letting me know @TwitchBronBron!  Should be a relatively simple fix in the Lexer, roughly where the two-word tokens are handled.  Probably just a `while(peek() === " ") { advance(); }` or similar before reading the next word.
