### ISSUE TITLE
Add runtime support for type designators

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#204]
PR #203 brings parser support for type designators, but not runtime support. The runtime should also support the enforcement of type designators.

**Comment by TwitchBronBron** [comment]
Did you mean to close this one? This is the "make the runtime enforce it" ticket...which #203 did not implement.

**Comment by TwitchBronBron** [comment]
This needs to be re-opened.  I accidentally referenced this ticket in PR #206, when it should have been #205

**Comment by sjbarag** [comment]
Whoopsies!  Thanks for letting me know.

**Comment by sjbarag** [comment]
Pretty sure I handled this in #240!  Closing it, but if I've messed that up please let me know (@)anyone!
