### ISSUE TITLE
Enforce code formatting lint rules for entire project

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#209]
After doing a few PRs for this project, I've noticed there are lots of little differences in formatting between the vscode auto-format and what is stored in this project. It would be nice to pick a standard, and enforce this with CI on every PR (through tslint). 

Getting tslint to enforce spacing is a bit quirky sometimes, but I found a few rules from npm that make this do-able in my `brightscript-language` [tslint.json file](https://github.com/TwitchBronBron/brightscript-language/blob/9c4a6fdf36451300152b972f7cc816ce5f006e4d/tslint.json)

I'd be more than happy to put together a PR with the lint enforcements, and also with all the tslint changes if you want?

**Comment by TwitchBronBron** [comment]
I'm working on this

**Comment by TwitchBronBron** [comment]
@sjbarag this can be closed now, right?

**Comment by sjbarag** [comment]
Yep!  Sorry about that
