### ISSUE TITLE
Allow sub with return type

### ISSUE THREAD

**Issue by triwav** [sjbarag/brs#220]
While against the main motivation of of using a sub IMO, it is legal in brightscript to do something like `sub getVideoUrl(videoFilename as String) as String`. Currently this will spit out `'Sub' functions are always void returns, and can't have 'as' clauses` which surprisingly is not true. Since this is valid brightscript, it should be allowed.

**Comment by chrisdp** [comment]
Just to add my input maybe this should changed to a be a warning rather than error status.

**Comment by TwitchBronBron** [comment]
I agree. Right now this error is coming from the parser (hence the 1000 error code). I'll open an issue over there and work towards getting it removed as an error, and then either the parser or this project can turn it into an error.

**Comment by sjbarag** [comment]
Oh no!  I could have sworn I'd checked this against the reference implementation before I added it here, but I guess not.  I agree on all parts here, in that this should definitely not be an error.  It probably shouldn't even be a warning at the language level — that seems like a job for a linter that consumes the AST this project's parser produces!  One day… :star2:

**Comment by triwav** [comment]
Yeah I have a code base now that uses it everywhere which I plan to switch over but if we could get this fixed it would make it much more obvious what the true issues are. 🙏

**Comment by sjbarag** [comment]
@triwav done!  Fix should be available in the next nightly release :smiley: 

Thanks for filing this!
