### ISSUE TITLE
increment/decrement statements error when last statement

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#223]
When an increment/decrement statement is the last item in a function, it produces a parse error. 

![image](https://user-images.githubusercontent.com/2544493/56891284-f8bfff80-6a49-11e9-9a23-90fc6bd038a5.png)

But adding any valid statement afterwords works just fine: 

![image](https://user-images.githubusercontent.com/2544493/56891321-10978380-6a4a-11e9-8b37-1d198f7529a9.png)

**Comment by sjbarag** [comment]
Sorry about that!  Should be fixed in the next nightly :smiley: 

Thanks for letting me know!
