### ISSUE TITLE
Colons after `if` statement condition cause parse failures

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#230]
Similar to #195 , a colon following an `if`/`else if` statement's condition is valid in RBI!  It looks shockingly like python, though I suspect that's not the intention 😉  Another case of "colons are treated like newlines most of the time!"  Minimal working example:

```brightscript
sub main()
    a = 1
    if a > 0:
        print "positive!"
    else if a < 0:
        print "negative!"
    else:
        print "tHaT NuMbEr iS ZeRo"
    end if
end sub
```

**Comment by TwitchBronBron** [comment]
@sjbarag I'm working on this
