### ISSUE TITLE
Regression: Sub with return type is broken again

### ISSUE THREAD

**Issue by TwitchBronBron** [sjbarag/brs#237]
`0.13.0-nightly.20190511` seems to have broken #220 ( sub with return type). 

Here's a test showing the issue:

```typescript
it('supports sub with return type', () => {
    let { tokens } = brs.lexer.Lexer.scan(`
        sub main() as integer
            return
        end sub
    `);

    let { statements, errors } = brs.parser.Parser.parse(tokens);
    expect(errors.length).toBe(0);
    expect(statements).toMatchSnapshot();
});
```

**Comment by TwitchBronBron** [comment]
Looks like it happened in my `library` pull request. Must have been a glitch in git's auto-merge. [Here's the section of code](https://github.com/sjbarag/brs/pull/216/files#diff-0af3c0ebba8c6d54ca06e99fa694be4fR347) that re-introduced the issue. Interesting that neither of us caught it.

**Comment by sjbarag** [comment]
:thinking: I thought I noticed something odd!  I'll get that fixed real fast.
