### ISSUE TITLE
Nested If Invalid Error

### ISSUE THREAD

**Issue by triwav** [sjbarag/brs#252]
The following will incorrectly spit out `Expected a statement to follow 'else'`
```
if true
    if true then t = 1
else
    ' empty line or line with just a comment causes crash
end if
```
It only happens if the inner if is a one line if and the else is empty which is edge casey but still compiles correctly so figured I'd report it.

**Comment by sjbarag** [comment]
Oh bummer!  Thanks for reporting this @triwav :smile:
