### ISSUE TITLE
Single line if else with dot setter

### ISSUE THREAD

**Issue by triwav** [sjbarag/brs#253]
`if true then m.top.visible = true else m.top.visible = false` spits out `Expected newline or ':' after dotted 'set' statement`

**Comment by sjbarag** [comment]
Well that's odd :open_mouth: Thanks for providing a test case! :heart:

**Comment by lvcabral** [comment]
I have a fix for this issue, will send a PR soon

**Comment by strattonbrazil** [comment]
Fixed in sjbarag/brs#309
