### ISSUE TITLE
conditional compile should not be case-sensitive

### ISSUE THREAD

**Issue by chrisdp** [sjbarag/brs#263]
Examples: 

![image](https://user-images.githubusercontent.com/9591618/59513851-18907300-8e92-11e9-9b39-8eccea9e24b9.png)

![image](https://user-images.githubusercontent.com/9591618/59513865-20501780-8e92-11e9-8e7a-f71b7e634306.png)

Should make sure to support:

```
#IF
#if

#ELSE
#else

#ELSEIF
#elseif

#ELSE IF
#else if

#ENDIF
#endif

#END IF
#end if
```

**Comment by sjbarag** [comment]
Thanks for reporting this!

**Comment by strattonbrazil** [comment]
This looks like a dupe of #404, which was resolved by lower casing the input text before checking. Tests look to handle this case. Closing.
