### ISSUE TITLE
Method ToString() for Array and AssociativeArray don't show string elements in quotes

### ISSUE THREAD

**Issue by lvcabral** [sjbarag/brs#275]
Roku debugger when printing the content of an array or aa, always shows string elements in quotes:

_<Component: roArray> =
[
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    "a"
    34
    1
    <Component: roArray>
]_

**Comment by lkipke** [comment]
Duplicate of #416
