### ISSUE TITLE
roString is missing one signature for the method SetString()

### ISSUE THREAD

**Issue by lvcabral** [sjbarag/brs#295]
There are two signatures for the SetString() method:
https://developer.roku.com/docs/references/brightscript/interfaces/ifstring.md#setstringvalue-as-string-as-void

https://developer.roku.com/docs/references/brightscript/interfaces/ifstringops.md#setstrings-as-string-len-as-integer-as-void

**Comment by alimnios72** [comment]
Fixed by #532
