### ISSUE TITLE
Interpreter messes up nested "if" handling when there is an "one line if" next to "else" or "endif"

### ISSUE THREAD

**Issue by lvcabral** [sjbarag/brs#309]
if type(component.TextAttrs.font) = "roString"
            font = m.fonts.Lookup(component.TextAttrs.font)
            if font = invalid then font = m.fonts.medium
        else if type(component.TextAttrs.font) = "roFont"
            font = component.TextAttrs.font
        else
            font = m.fonts.reg.GetDefaultFont()
        end if

**Comment by lvcabral** [comment]
In the code above, the line `if font=invalid then font=m.fonts.medium` messes up the interpreter (with not exception)  and the logic implies the `else` below is related to the `inline if`

**Comment by strattonbrazil** [comment]
Fixed in sjbarag/brs#309.

**Comment by sjbarag** [comment]
> Fixed in #309.

Looks like #345 fixed it — this is 309 😜

**Comment by sjbarag** [comment]
Thanks for the PR, @lvcabral!
