### ISSUE TITLE
Make a list of missing components/functions/functionality

### ISSUE THREAD

**Issue by lkipke** [sjbarag/brs#463]
# Summary

Right now when a test breaks, it's pretty difficult for a developer to tell whether something went wrong in the unit test, or something went wrong in `brs`. Particularly, not every component is implemented, and some components (i.e. `MarkupGrid`) are just "skeletons" that don't actually behave like they do in BrightScript.

We should keep a list of all of the components and global functions that are not yet implemented so that it's easily discoverable for developers.

(Also, it'd be really cool if we were able to somehow leverage that in the code, so we could print messages to the user like "Error: Tried to use FooComponent, but it is not implemented")

**Comment by sjbarag** [comment]
d'oh, that wasn't the full list — that's what I get for manually linking.
