### ISSUE TITLE
Implement multiplicative global math functions

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#47]
Yet another subset of #43.  Covers:

* `Exp(x as Float) as Float`
* `Log(x as Float) as Float`
* `Sqr(x as Float) as Float`

And these two non-multiplicative functions because I don't know where else to put them :man_shrugging: 
* `Rnd(range as Integer) as Integer`
* `Rnd(0) as Float`

**Comment by strattonbrazil** [comment]
Implemented here:
https://github.com/sjbarag/brs/commit/10efa06b43794c36ce1bf37eeb7014d72d8a698f
