### ISSUE TITLE
Add support for relative URIs in `<script>` tags

### ISSUE THREAD

**Issue by sjbarag** [sjbarag/brs#471]
SGDEX uses relative paths for the `uri` attribute of its `<script>` tags, which is perfectly valid in RBI!  We should support that here as well.

Example error, from https://github.com/hulu/roca/issues/35

```
Interpreter found an error:  Error: Encountered an error when parsing component ButtonBar: TypeError [ERR_INVALID_URL]: Invalid URL: ButtonBar.brs
    at componentDefinitions.forEach (/Users/user/Projects/roca-test-roku/nod_modules/brs/lib/index.js:66:19)
```

Parsing through https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/extensions/SGDEX/ButtonBar/ButtonBar.xml with https://github.com/rokudev/SceneGraphDeveloperExtensions/blob/master/extensions/SGDEX/ButtonBar/ButtonBar.brs next to it should be enough to repro this bug

**Comment by sjbarag** [comment]
@adheus feel free to track this issue for notifications!

**Comment by adheus** [comment]
Sure. Thank you!

**Comment by adheus** [comment]
In case anyone wants to quickly port a project. I've created a Python GIST to patch this(don't run this unless you can revert any changes):

https://gist.github.com/adheus/aed5d859da761f4f36e89998c4354b35
