### ISSUE TITLE
Single-line if statements don't allow multiple statements in "then" block

### ISSUE THREAD

**Issue by adheus** [sjbarag/brs#481]
The following code:
```brightscript
array = [ "a", "b", "c" ]
index = 2
found = false
for i = 0 to array.Count() - 1
    ?i
    if i = index then found = true : exit for
next
?found
```
has the following outputs on a Roku device:
```
 0
 1
 2
true
```

while on **brs**:
```
0
false
```

-----

Minimum working example:

```brightscript
sub main()
    if false then nop(): print "#481 still repro's": return
    print "#481 fixed"
end sub

sub nop()
end sub
```

**Comment by sjbarag** [comment]
Interesting!  Looks like this doesn't have anything to do with `next` (which we treat [as a synonym for `end for`](https://github.com/sjbarag/brs/pull/151)), but with how we handle single-line `if` statements.  We're only treating the next statement as part of the "then" block, and all remaining statements are outside of that, which appears to not match the reference implementation.

Put another way, `brs` currently considers that code equivalent to:

```brightscript
' wrong parse:
for i = 0 to array.count() - 1
    ?i
    if i = index then
        found = true
    end if
    exit for
end for
```

but it should _actually_ be equivalent to:

```brightscript
' correct parse:
for i = 0 to array.count() - 1
    ?i
    if i = index then
        found = true
        exit for
    end if
end for
```

The smallest working example I can find to demonstrate this is:

```brightscript
sub main()
    for i = 0 to 5
        if i = 4 then print i : print "#481 still repro's" : exit for
        print "#481 fixed"
    end for
end sub
```
