### ISSUE TITLE
Calling type() on a roSGNode instance returns a different type name

### ISSUE THREAD

**Issue by adheus** [sjbarag/brs#482]
The following code has a different output when compared to the one of a Roku device:

```
node =  CreateObject("roSGNode", "SomeNode")
?type(node)
```

**Roku:**
```
roSGNode
```

**brs:**
```
Node
```

**Comment by vbuchii** [comment]
Also, we have different output if we call `type()` function on an uninitialized object:

**Roku:**
`<uninitialized>`

**brs:**
`<UNINITIALIZED>`
