### ISSUE TITLE
callFunc() only supports a single parameter

### ISSUE THREAD

**Issue by adheus** [sjbarag/brs#483]
Calling a `node.callFunc("funcName", param1, param2)` with more than one parameter raises the folllowing error:

```
Provided arguments don't match callfunc's signature.
    function callfunc(functionname as String, [functionargs as Dynamic]) as Dynamic:
        * callfunc accepts at most 2 arguments, but received 3.Runtime error encountered in BRS implementation:  Error: Something terrible happened and we didn't throw a `BlockEnd` instance.
```
This should be supported, accordingly to Roku docs:

> Any context from the caller can be passed via one or more method parameters, which may be of any type (previously, callFunc() only supported a single associative array parameter).

**Comment by vbuchii** [comment]
I'd like to add here, that in `BrightScript` we can call `callFunc()` without any parameters: `node.callFunc("funcName")`, but `BRS` doesn't support this.
