### ISSUE TITLE
Several asserts in scope of the one test case don't work properly

### ISSUE THREAD

**Issue by vbuchii** [sjbarag/brs#506]
If we make several asserts within one test case, and one of them fails, the others that follow will not be fulfilled. So, while running the test, we do not see any information about the following asserts until we fix the error or comment it.

**Comment by alimnios72** [comment]
Hi @vbuchii thanks for finding this issue, assertions and test cases are actually handled in [roca](https://github.com/hulu/roca), can you please open the [issue](https://github.com/hulu/roca/issues) in that repo?

**Comment by vbuchii** [comment]
Sure, will do

**Comment by vbuchii** [comment]
Opened an [issue](https://github.com/hulu/roca/issues/48) in roca.
