### ISSUE TITLE
Implement the same 'typecasting' as on Roku

### ISSUE THREAD

**Issue by vbuchii** [sjbarag/brs#609]
In interpreter, we can't pass `double`, `longInteger` if the declared argument type is `integer` , also we can not cast `double` to `float`, `longInteger` to `float`, `integer` to `double`, `longinteger` to `double`. On Roku all types among themselves compatible.
Please see #600 for more context.

**Comment by sjbarag** [comment]
Critically, this includes comparisons with `RoLongInteger` as well.

**Comment by sjbarag** [comment]
Forgot to link this to #620 before I merged!
