### ISSUE TITLE
Supported methods are not available as field names

### ISSUE THREAD

**Issue by vbuchii** [sjbarag/brs#621]
Let's say that we have next object:
contentNodes = {}

Supported methods are not available as fields name

? "contentNodes.items = " contentNodes.items
? "contentNodes.count = " contentNodes.count

### On Roku:
```
    contentnodes.items = invalid
    contentnodes.count = invalid
```

### On BRS:
```
   contentnodes.items = [Function items]
   contentnodes.count = [Function count]
```

So, on Roku expression: `if contentnodes.items = invalid or contentnodes.items[0] = invalid then` is valid but while running tests not.

**Comment by lkipke** [comment]
Closing as a duplicate of #437
