### ISSUE TITLE
Implement global reflective functions to return interface information

### ISSUE THREAD

**Issue by strattonbrazil** [sjbarag/brs#78]
See the [BrightScript documentation](https://sdkdocs.roku.com/display/sdkdoc/Global+Utility+Functions#GlobalUtilityFunctions-GetInterface(objectasObject,ifnameasString)asInterface) for details on what each one does, but this should cover:

* `GetInterface(object as Object, ifname as String) as Interface`
* `FindMemberFunction(object as Object, funName as String) As Interface`

This is currently blocked until objects are implemented, but when implemented objects one should keep this function in mind as it will need access to which interface a function came from.

**Comment by sjbarag** [comment]
Now that `RoString` exists (#254), this should be possible!  `GetInterface` can basically check the `interfaces` array on a `BrsComponent`.

`FindMemberFunction` won't work just yet though — looks like we'll need more than just strings for the interfaces we track there.
